# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='brus',
            name='money',
        ),
        migrations.AddField(
            model_name='brus',
            name='cost',
            field=models.IntegerField(default=15),
        ),
    ]
