# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0002_auto_20160225_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brus',
            name='name',
        ),
        migrations.AddField(
            model_name='brus',
            name='soda',
            field=models.CharField(default='', max_length=20),
        ),
    ]
